#!/system/bin/sh
#
# ota
#   - This file allows MIUI updater to use amonra or cwm recoveries to flash
#     OTA updates by writing to the proper paths used by either cwm or amonra
#
#     This script defaults to cwm recovery but can easily be changed
#
# Copyright (c) 2011 MIUI.us
# Written by n_i_x

CMD='/system/xbin/cwmota'

if [ -e /sdcard/MIUI/ota.config.amonra ]
then
  CMD='/system/xbin/amonraota'
elif [ -e /sdcard/MIUI/ota.config.cwm ]
then
  CMD='/system/xbin/cwmota'
fi

echo $CMD $@
